#ifndef DEF_CONSTANTS
#define DEF_CONSTANTS

#define MAX_ROW 10
#define MAX_COL 10
#define CELL_COUNT MAX_ROW*MAX_COL
#define CELL_SIZE 60

enum Move { ILLEGAL, SIMPLE, SINGLE_CAPTURE, MANY_CAPTURE };

#endif