######################################################################
# Automatically generated by qmake (2.01a) lun. janv. 30 13:38:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
