######################################################################
# Automatically generated by qmake (2.01a) lun. févr. 6 13:38:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network core

# Input
HEADERS += 	TcpServer.h \
			TcpClient.h \
			Server.h \
			Game.h \
			Brain.h

SOURCES += 	main.cpp \
			TcpServer.cpp \
			TcpClient.cpp \
			Server.cpp \
			Game.cpp \
			Brain.cpp
